"""Calculating Protein Mass"""

# Create Monoisotopic Table from file 

mol_weight = {} # empty dictionary 

with open ("/Users/annatswater/Desktop/Monoisotopic_Table.txt", "r+") as f:

    for line in f:

        line = line.split()

        mol_weight.update({line[0]: float(line[1])}) # parse file result in string, so need to float() it


string_prot = "ESSPQCFQQHNIETAMEPNKHLARYHMWDHDVRYYMWERHEWEPCWNHCDQTCLRWHEAWRRMFMVRPWSNDNRIVCDCMCQHMQTQIWLVEDQWGKECIFENDLPKECNTYKPHRRPNVCRQSEKGMRRILRHTMYFWCMQKCDKWFAFESHLSYDDQQYIVYPRPAHDMDIKLSHVNGCHYGWGKHCEAQMMFTPELGRKYYNFGPQKPRHVDIVRFVDLWHFYVWMAVFNHAVQAIEDLLQYLQQEARHYGVLAFTAHVNRHGVSTRLHLTWRGWYPMTVKNINAEIQWAVSKDVKWREVCKACQDQLMDWYSWHDTCSIASGLMTMPPPLTSSRPCFIKGCSIWWLPHWNLGYLCITEEFTDHGNETRFKPCHGYVIYAYPGWPIDGHYILRHSESRSNNHAAAATFRDTGGGSFPQCMHDHRLDCTLAMTNMIVVRLACVWEFLWGPAQIFTQSTFDCRDGPAGKDNTISKLWNTWSGSVPKPAYMLRRHIHHEAAQMFGARTVVRVRDEPDHRPIYNSFIIMHSLFNIFMLIHVSCFPVLHFCRSTWQCGVHHVDEFACGVASCSISFTDLSYATKDRDFQMWEKIHNCYEGYHFSVYRWVNRLYMMGRWAETDTRDLDDAPLHCQFEMNTFNDNYHDNAWRNMGDESDGFMNLRYFNMTDCDYFYMWEGCPRIIVTWETLQDQKDFDVDHDRPISWEGLCWSDWTYMECFLNDTQAKVTGNMVVRAFIYPYPPDVKKAPNQVPDRSTFHMWLYYLFCIVQETDATDNPFEEEELFAGFYLIEHGSWSRKQYWHIQMNADNWFSPGGSVFRAWVIADCKDVWHKQINKEVQKYLNRRAKKYLICWKNCLGHNHDWVYYLGIHIHHSEQYFMLLDPKGQYTNKKYFWWNGLVRQPMRSRV"

total_mol = 0

for char in string_prot:

    total_mol += mol_weight.get(char)# dict.get(key) returns value
    
print("{:.3f}".format(total_mol))

